spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kursachBD
    username: root
    password: 123

  liquibase:
    change-log: db/changelog/main-changelog.xml

server:
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: framework
  port: 8448

my-jwt:
  key: I2ZLgzZUSSXOlLbM6DD84qYBT/CvLfRANuq5aaHAYWE=

yandex:
  disk:
    oauth-token: y0__wgBEMbV7_cCGKONNCDZpNfuETGuWkwxLscPCPjIyW6gbbsFSg_y
    upload-path: /backups
pg:
  dump-path: F:\PostgreSQL\16\bin\pg_dump.exe

backup:
  file-location: src/main/resources/backups